# Generated by Django 3.2.8 on 2023-03-07 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, max_length=11)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2023, 3, 7, 13, 28, 34, 70571))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2023, 3, 7, 13, 28, 34, 70571))),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
    ]
